//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInstruction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int InstructionID { get; set; }
    
        public virtual Instruction Instruction { get; set; }
        public virtual User User { get; set; }
    }
}
